/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "MobileAuth.h"
#import "MobileCommon.h"
#import "MobileCommon.h"

@interface LoginResponse : NSObject <NSCoding> {
  Response * __response;
  User * __userDetails;

  BOOL __response_isset;
  BOOL __userDetails_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=userDetails, setter=setUserDetails:) User * userDetails;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response userDetails: (User *) userDetails;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (User *) userDetails;
- (void) setUserDetails: (User *) userDetails;
#endif
- (BOOL) userDetailsIsSet;

@end

@protocol MobileAuth <NSObject>
- (LoginResponse *) login: (NSString *) email password: (NSString *) password;  // throws TException
@end

@interface MobileAuthClient : NSObject <MobileAuth> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface MobileAuthProcessor : NSObject <TProcessor> {
  id <MobileAuth> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithMobileAuth: (id <MobileAuth>) service;
- (id<MobileAuth>) service;
@end

@interface MobileAuthConstants : NSObject {
}
@end
