/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "MobileCommon.h"

enum ReviewType {
  ReviewType_Kiosk = 1,
  ReviewType_RequestReview = 2,
  ReviewType_Social = 3
};

enum MediaType {
  MediaType_Photo = 1,
  MediaType_Video = 2
};

enum Sentiment {
  Sentiment_Positive = 0,
  Sentiment_Neutral = 1,
  Sentiment_Negative = 2,
  Sentiment_None = 3
};

typedef NSString * SourceCode;

@interface SummaryValue : NSObject <NSCoding> {
  NSString * __name;
  double __value;
  NSMutableDictionary * __addlProps;

  BOOL __name_isset;
  BOOL __value_isset;
  BOOL __addlProps_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=value, setter=setValue:) double value;
@property (nonatomic, retain, getter=addlProps, setter=setAddlProps:) NSMutableDictionary * addlProps;
#endif

- (id) init;
- (id) initWithName: (NSString *) name value: (double) value addlProps: (NSMutableDictionary *) addlProps;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) value;
- (void) setValue: (double) value;
#endif
- (BOOL) valueIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) addlProps;
- (void) setAddlProps: (NSMutableDictionary *) addlProps;
#endif
- (BOOL) addlPropsIsSet;

@end

@interface ReviewResponse : NSObject <NSCoding> {
  NSString * __reviewResponseComment;
  int64_t __reviewResponseCreateDt;
  NSString * __reviewResponseName;

  BOOL __reviewResponseComment_isset;
  BOOL __reviewResponseCreateDt_isset;
  BOOL __reviewResponseName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=reviewResponseComment, setter=setReviewResponseComment:) NSString * reviewResponseComment;
@property (nonatomic, getter=reviewResponseCreateDt, setter=setReviewResponseCreateDt:) int64_t reviewResponseCreateDt;
@property (nonatomic, retain, getter=reviewResponseName, setter=setReviewResponseName:) NSString * reviewResponseName;
#endif

- (id) init;
- (id) initWithReviewResponseComment: (NSString *) reviewResponseComment reviewResponseCreateDt: (int64_t) reviewResponseCreateDt reviewResponseName: (NSString *) reviewResponseName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) reviewResponseComment;
- (void) setReviewResponseComment: (NSString *) reviewResponseComment;
#endif
- (BOOL) reviewResponseCommentIsSet;

#if !__has_feature(objc_arc)
- (int64_t) reviewResponseCreateDt;
- (void) setReviewResponseCreateDt: (int64_t) reviewResponseCreateDt;
#endif
- (BOOL) reviewResponseCreateDtIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewResponseName;
- (void) setReviewResponseName: (NSString *) reviewResponseName;
#endif
- (BOOL) reviewResponseNameIsSet;

@end

@interface Review : NSObject <NSCoding> {
  NSString * __id;
  NSString * __locationName;
  NSString * __reviewerId;
  NSString * __reviewerName;
  NSString * __reviewerPhotoUrl;
  NSString * __reviewerProfileUrl;
  NSString * __reviewerEmail;
  NSString * __reviewerPhone;
  double __rating;
  double __normalizedRating;
  NSString * __date;
  int64_t __ratedTimestamp;
  int64_t __addedTimestamp;
  int64_t __updatedTimestamp;
  NSString * __comment;
  NSMutableArray * __tags;
  SourceCode __sourceId;
  NSString * __sourceName;
  NSString * __sourceSmallIconPath;
  NSString * __sourceLargeIconPath;
  RatingScale * __sourceOverallRS;
  NSMutableDictionary * __sourceSubRatingRS;
  SourceGroup __sourceGroup;
  BOOL __isSourceRequestReviewable;
  NSString * __sourceURL;
  SourceCode __originSourceId;
  SourceCode __originSourceName;
  NSString * __originSourceURL;
  NSMutableArray * __properties;
  NSString * __commentTitle;
  int64_t __publishDate;
  BOOL __published;
  BOOL __requested;
  int32_t __numReplies;
  int64_t __lastReplyDate;
  int32_t __nps;
  NSMutableArray * __rresponses;
  NSString * __npsBgColor;
  BOOL __hasResponded;
  BOOL __isStarRatingEnabled;
  NSMutableArray * __allowedActions;
  int __sentiment;

  BOOL __id_isset;
  BOOL __locationName_isset;
  BOOL __reviewerId_isset;
  BOOL __reviewerName_isset;
  BOOL __reviewerPhotoUrl_isset;
  BOOL __reviewerProfileUrl_isset;
  BOOL __reviewerEmail_isset;
  BOOL __reviewerPhone_isset;
  BOOL __rating_isset;
  BOOL __normalizedRating_isset;
  BOOL __date_isset;
  BOOL __ratedTimestamp_isset;
  BOOL __addedTimestamp_isset;
  BOOL __updatedTimestamp_isset;
  BOOL __comment_isset;
  BOOL __tags_isset;
  BOOL __sourceId_isset;
  BOOL __sourceName_isset;
  BOOL __sourceSmallIconPath_isset;
  BOOL __sourceLargeIconPath_isset;
  BOOL __sourceOverallRS_isset;
  BOOL __sourceSubRatingRS_isset;
  BOOL __sourceGroup_isset;
  BOOL __isSourceRequestReviewable_isset;
  BOOL __sourceURL_isset;
  BOOL __originSourceId_isset;
  BOOL __originSourceName_isset;
  BOOL __originSourceURL_isset;
  BOOL __properties_isset;
  BOOL __commentTitle_isset;
  BOOL __publishDate_isset;
  BOOL __published_isset;
  BOOL __requested_isset;
  BOOL __numReplies_isset;
  BOOL __lastReplyDate_isset;
  BOOL __nps_isset;
  BOOL __rresponses_isset;
  BOOL __npsBgColor_isset;
  BOOL __hasResponded_isset;
  BOOL __isStarRatingEnabled_isset;
  BOOL __allowedActions_isset;
  BOOL __sentiment_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=locationName, setter=setLocationName:) NSString * locationName;
@property (nonatomic, retain, getter=reviewerId, setter=setReviewerId:) NSString * reviewerId;
@property (nonatomic, retain, getter=reviewerName, setter=setReviewerName:) NSString * reviewerName;
@property (nonatomic, retain, getter=reviewerPhotoUrl, setter=setReviewerPhotoUrl:) NSString * reviewerPhotoUrl;
@property (nonatomic, retain, getter=reviewerProfileUrl, setter=setReviewerProfileUrl:) NSString * reviewerProfileUrl;
@property (nonatomic, retain, getter=reviewerEmail, setter=setReviewerEmail:) NSString * reviewerEmail;
@property (nonatomic, retain, getter=reviewerPhone, setter=setReviewerPhone:) NSString * reviewerPhone;
@property (nonatomic, getter=rating, setter=setRating:) double rating;
@property (nonatomic, getter=normalizedRating, setter=setNormalizedRating:) double normalizedRating;
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
@property (nonatomic, getter=ratedTimestamp, setter=setRatedTimestamp:) int64_t ratedTimestamp;
@property (nonatomic, getter=addedTimestamp, setter=setAddedTimestamp:) int64_t addedTimestamp;
@property (nonatomic, getter=updatedTimestamp, setter=setUpdatedTimestamp:) int64_t updatedTimestamp;
@property (nonatomic, retain, getter=comment, setter=setComment:) NSString * comment;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
@property (nonatomic, retain, getter=sourceId, setter=setSourceId:) SourceCode sourceId;
@property (nonatomic, retain, getter=sourceName, setter=setSourceName:) NSString * sourceName;
@property (nonatomic, retain, getter=sourceSmallIconPath, setter=setSourceSmallIconPath:) NSString * sourceSmallIconPath;
@property (nonatomic, retain, getter=sourceLargeIconPath, setter=setSourceLargeIconPath:) NSString * sourceLargeIconPath;
@property (nonatomic, retain, getter=sourceOverallRS, setter=setSourceOverallRS:) RatingScale * sourceOverallRS;
@property (nonatomic, retain, getter=sourceSubRatingRS, setter=setSourceSubRatingRS:) NSMutableDictionary * sourceSubRatingRS;
@property (nonatomic, retain, getter=sourceGroup, setter=setSourceGroup:) SourceGroup sourceGroup;
@property (nonatomic, getter=isSourceRequestReviewable, setter=setIsSourceRequestReviewable:) BOOL isSourceRequestReviewable;
@property (nonatomic, retain, getter=sourceURL, setter=setSourceURL:) NSString * sourceURL;
@property (nonatomic, retain, getter=originSourceId, setter=setOriginSourceId:) SourceCode originSourceId;
@property (nonatomic, retain, getter=originSourceName, setter=setOriginSourceName:) SourceCode originSourceName;
@property (nonatomic, retain, getter=originSourceURL, setter=setOriginSourceURL:) NSString * originSourceURL;
@property (nonatomic, retain, getter=properties, setter=setProperties:) NSMutableArray * properties;
@property (nonatomic, retain, getter=commentTitle, setter=setCommentTitle:) NSString * commentTitle;
@property (nonatomic, getter=publishDate, setter=setPublishDate:) int64_t publishDate;
@property (nonatomic, getter=published, setter=setPublished:) BOOL published;
@property (nonatomic, getter=requested, setter=setRequested:) BOOL requested;
@property (nonatomic, getter=numReplies, setter=setNumReplies:) int32_t numReplies;
@property (nonatomic, getter=lastReplyDate, setter=setLastReplyDate:) int64_t lastReplyDate;
@property (nonatomic, getter=nps, setter=setNps:) int32_t nps;
@property (nonatomic, retain, getter=rresponses, setter=setRresponses:) NSMutableArray * rresponses;
@property (nonatomic, retain, getter=npsBgColor, setter=setNpsBgColor:) NSString * npsBgColor;
@property (nonatomic, getter=hasResponded, setter=setHasResponded:) BOOL hasResponded;
@property (nonatomic, getter=isStarRatingEnabled, setter=setIsStarRatingEnabled:) BOOL isStarRatingEnabled;
@property (nonatomic, retain, getter=allowedActions, setter=setAllowedActions:) NSMutableArray * allowedActions;
@property (nonatomic, getter=sentiment, setter=setSentiment:) int sentiment;
#endif

- (id) init;
- (id) initWithId: (NSString *) id locationName: (NSString *) locationName reviewerId: (NSString *) reviewerId reviewerName: (NSString *) reviewerName reviewerPhotoUrl: (NSString *) reviewerPhotoUrl reviewerProfileUrl: (NSString *) reviewerProfileUrl reviewerEmail: (NSString *) reviewerEmail reviewerPhone: (NSString *) reviewerPhone rating: (double) rating normalizedRating: (double) normalizedRating date: (NSString *) date ratedTimestamp: (int64_t) ratedTimestamp addedTimestamp: (int64_t) addedTimestamp updatedTimestamp: (int64_t) updatedTimestamp comment: (NSString *) comment tags: (NSMutableArray *) tags sourceId: (SourceCode) sourceId sourceName: (NSString *) sourceName sourceSmallIconPath: (NSString *) sourceSmallIconPath sourceLargeIconPath: (NSString *) sourceLargeIconPath sourceOverallRS: (RatingScale *) sourceOverallRS sourceSubRatingRS: (NSMutableDictionary *) sourceSubRatingRS sourceGroup: (SourceGroup) sourceGroup isSourceRequestReviewable: (BOOL) isSourceRequestReviewable sourceURL: (NSString *) sourceURL originSourceId: (SourceCode) originSourceId originSourceName: (SourceCode) originSourceName originSourceURL: (NSString *) originSourceURL properties: (NSMutableArray *) properties commentTitle: (NSString *) commentTitle publishDate: (int64_t) publishDate published: (BOOL) published requested: (BOOL) requested numReplies: (int32_t) numReplies lastReplyDate: (int64_t) lastReplyDate nps: (int32_t) nps rresponses: (NSMutableArray *) rresponses npsBgColor: (NSString *) npsBgColor hasResponded: (BOOL) hasResponded isStarRatingEnabled: (BOOL) isStarRatingEnabled allowedActions: (NSMutableArray *) allowedActions sentiment: (int) sentiment;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) locationName;
- (void) setLocationName: (NSString *) locationName;
#endif
- (BOOL) locationNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerId;
- (void) setReviewerId: (NSString *) reviewerId;
#endif
- (BOOL) reviewerIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerName;
- (void) setReviewerName: (NSString *) reviewerName;
#endif
- (BOOL) reviewerNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerPhotoUrl;
- (void) setReviewerPhotoUrl: (NSString *) reviewerPhotoUrl;
#endif
- (BOOL) reviewerPhotoUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerProfileUrl;
- (void) setReviewerProfileUrl: (NSString *) reviewerProfileUrl;
#endif
- (BOOL) reviewerProfileUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerEmail;
- (void) setReviewerEmail: (NSString *) reviewerEmail;
#endif
- (BOOL) reviewerEmailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewerPhone;
- (void) setReviewerPhone: (NSString *) reviewerPhone;
#endif
- (BOOL) reviewerPhoneIsSet;

#if !__has_feature(objc_arc)
- (double) rating;
- (void) setRating: (double) rating;
#endif
- (BOOL) ratingIsSet;

#if !__has_feature(objc_arc)
- (double) normalizedRating;
- (void) setNormalizedRating: (double) normalizedRating;
#endif
- (BOOL) normalizedRatingIsSet;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

#if !__has_feature(objc_arc)
- (int64_t) ratedTimestamp;
- (void) setRatedTimestamp: (int64_t) ratedTimestamp;
#endif
- (BOOL) ratedTimestampIsSet;

#if !__has_feature(objc_arc)
- (int64_t) addedTimestamp;
- (void) setAddedTimestamp: (int64_t) addedTimestamp;
#endif
- (BOOL) addedTimestampIsSet;

#if !__has_feature(objc_arc)
- (int64_t) updatedTimestamp;
- (void) setUpdatedTimestamp: (int64_t) updatedTimestamp;
#endif
- (BOOL) updatedTimestampIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comment;
- (void) setComment: (NSString *) comment;
#endif
- (BOOL) commentIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

#if !__has_feature(objc_arc)
- (SourceCode) sourceId;
- (void) setSourceId: (SourceCode) sourceId;
#endif
- (BOOL) sourceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceName;
- (void) setSourceName: (NSString *) sourceName;
#endif
- (BOOL) sourceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceSmallIconPath;
- (void) setSourceSmallIconPath: (NSString *) sourceSmallIconPath;
#endif
- (BOOL) sourceSmallIconPathIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceLargeIconPath;
- (void) setSourceLargeIconPath: (NSString *) sourceLargeIconPath;
#endif
- (BOOL) sourceLargeIconPathIsSet;

#if !__has_feature(objc_arc)
- (RatingScale *) sourceOverallRS;
- (void) setSourceOverallRS: (RatingScale *) sourceOverallRS;
#endif
- (BOOL) sourceOverallRSIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) sourceSubRatingRS;
- (void) setSourceSubRatingRS: (NSMutableDictionary *) sourceSubRatingRS;
#endif
- (BOOL) sourceSubRatingRSIsSet;

#if !__has_feature(objc_arc)
- (SourceGroup) sourceGroup;
- (void) setSourceGroup: (SourceGroup) sourceGroup;
#endif
- (BOOL) sourceGroupIsSet;

#if !__has_feature(objc_arc)
- (BOOL) isSourceRequestReviewable;
- (void) setIsSourceRequestReviewable: (BOOL) isSourceRequestReviewable;
#endif
- (BOOL) isSourceRequestReviewableIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;
#endif
- (BOOL) sourceURLIsSet;

#if !__has_feature(objc_arc)
- (SourceCode) originSourceId;
- (void) setOriginSourceId: (SourceCode) originSourceId;
#endif
- (BOOL) originSourceIdIsSet;

#if !__has_feature(objc_arc)
- (SourceCode) originSourceName;
- (void) setOriginSourceName: (SourceCode) originSourceName;
#endif
- (BOOL) originSourceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) originSourceURL;
- (void) setOriginSourceURL: (NSString *) originSourceURL;
#endif
- (BOOL) originSourceURLIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) properties;
- (void) setProperties: (NSMutableArray *) properties;
#endif
- (BOOL) propertiesIsSet;

#if !__has_feature(objc_arc)
- (NSString *) commentTitle;
- (void) setCommentTitle: (NSString *) commentTitle;
#endif
- (BOOL) commentTitleIsSet;

#if !__has_feature(objc_arc)
- (int64_t) publishDate;
- (void) setPublishDate: (int64_t) publishDate;
#endif
- (BOOL) publishDateIsSet;

#if !__has_feature(objc_arc)
- (BOOL) published;
- (void) setPublished: (BOOL) published;
#endif
- (BOOL) publishedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) requested;
- (void) setRequested: (BOOL) requested;
#endif
- (BOOL) requestedIsSet;

#if !__has_feature(objc_arc)
- (int32_t) numReplies;
- (void) setNumReplies: (int32_t) numReplies;
#endif
- (BOOL) numRepliesIsSet;

#if !__has_feature(objc_arc)
- (int64_t) lastReplyDate;
- (void) setLastReplyDate: (int64_t) lastReplyDate;
#endif
- (BOOL) lastReplyDateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) nps;
- (void) setNps: (int32_t) nps;
#endif
- (BOOL) npsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) rresponses;
- (void) setRresponses: (NSMutableArray *) rresponses;
#endif
- (BOOL) rresponsesIsSet;

#if !__has_feature(objc_arc)
- (NSString *) npsBgColor;
- (void) setNpsBgColor: (NSString *) npsBgColor;
#endif
- (BOOL) npsBgColorIsSet;

#if !__has_feature(objc_arc)
- (BOOL) hasResponded;
- (void) setHasResponded: (BOOL) hasResponded;
#endif
- (BOOL) hasRespondedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) isStarRatingEnabled;
- (void) setIsStarRatingEnabled: (BOOL) isStarRatingEnabled;
#endif
- (BOOL) isStarRatingEnabledIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) allowedActions;
- (void) setAllowedActions: (NSMutableArray *) allowedActions;
#endif
- (BOOL) allowedActionsIsSet;

#if !__has_feature(objc_arc)
- (int) sentiment;
- (void) setSentiment: (int) sentiment;
#endif
- (BOOL) sentimentIsSet;

@end

@interface SummaryCell : NSObject <NSCoding> {
  NSString * __name;
  NSMutableArray * __values;

  BOOL __name_isset;
  BOOL __values_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=values, setter=setValues:) NSMutableArray * values;
#endif

- (id) init;
- (id) initWithName: (NSString *) name values: (NSMutableArray *) values;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) values;
- (void) setValues: (NSMutableArray *) values;
#endif
- (BOOL) valuesIsSet;

@end

@interface ReferenceData : NSObject <NSCoding> {
  NSMutableArray * __authLocations;
  NSMutableArray * __allSources;

  BOOL __authLocations_isset;
  BOOL __allSources_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=authLocations, setter=setAuthLocations:) NSMutableArray * authLocations;
@property (nonatomic, retain, getter=allSources, setter=setAllSources:) NSMutableArray * allSources;
#endif

- (id) init;
- (id) initWithAuthLocations: (NSMutableArray *) authLocations allSources: (NSMutableArray *) allSources;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSMutableArray *) authLocations;
- (void) setAuthLocations: (NSMutableArray *) authLocations;
#endif
- (BOOL) authLocationsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) allSources;
- (void) setAllSources: (NSMutableArray *) allSources;
#endif
- (BOOL) allSourcesIsSet;

@end

@interface PostUser : NSObject <NSCoding> {
  NSString * __id;
  NSString * __locationName;
  NSString * __userName;
  NSString * __displayName;
  NSString * __location;
  NSString * __photoUrl;
  NSString * __profileUrl;

  BOOL __id_isset;
  BOOL __locationName_isset;
  BOOL __userName_isset;
  BOOL __displayName_isset;
  BOOL __location_isset;
  BOOL __photoUrl_isset;
  BOOL __profileUrl_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=locationName, setter=setLocationName:) NSString * locationName;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=displayName, setter=setDisplayName:) NSString * displayName;
@property (nonatomic, retain, getter=location, setter=setLocation:) NSString * location;
@property (nonatomic, retain, getter=photoUrl, setter=setPhotoUrl:) NSString * photoUrl;
@property (nonatomic, retain, getter=profileUrl, setter=setProfileUrl:) NSString * profileUrl;
#endif

- (id) init;
- (id) initWithId: (NSString *) id locationName: (NSString *) locationName userName: (NSString *) userName displayName: (NSString *) displayName location: (NSString *) location photoUrl: (NSString *) photoUrl profileUrl: (NSString *) profileUrl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) locationName;
- (void) setLocationName: (NSString *) locationName;
#endif
- (BOOL) locationNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
#endif
- (BOOL) userNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) displayName;
- (void) setDisplayName: (NSString *) displayName;
#endif
- (BOOL) displayNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) location;
- (void) setLocation: (NSString *) location;
#endif
- (BOOL) locationIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photoUrl;
- (void) setPhotoUrl: (NSString *) photoUrl;
#endif
- (BOOL) photoUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) profileUrl;
- (void) setProfileUrl: (NSString *) profileUrl;
#endif
- (BOOL) profileUrlIsSet;

@end

@interface Media : NSObject <NSCoding> {
  NSString * __id;
  int __type;
  NSString * __photoUrl;
  NSString * __expandedUrl;
  NSString * __displayUrl;
  int32_t __offset;
  int32_t __length;
  NSMutableDictionary * __properties;

  BOOL __id_isset;
  BOOL __type_isset;
  BOOL __photoUrl_isset;
  BOOL __expandedUrl_isset;
  BOOL __displayUrl_isset;
  BOOL __offset_isset;
  BOOL __length_isset;
  BOOL __properties_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, retain, getter=photoUrl, setter=setPhotoUrl:) NSString * photoUrl;
@property (nonatomic, retain, getter=expandedUrl, setter=setExpandedUrl:) NSString * expandedUrl;
@property (nonatomic, retain, getter=displayUrl, setter=setDisplayUrl:) NSString * displayUrl;
@property (nonatomic, getter=offset, setter=setOffset:) int32_t offset;
@property (nonatomic, getter=length, setter=setLength:) int32_t length;
@property (nonatomic, retain, getter=properties, setter=setProperties:) NSMutableDictionary * properties;
#endif

- (id) init;
- (id) initWithId: (NSString *) id type: (int) type photoUrl: (NSString *) photoUrl expandedUrl: (NSString *) expandedUrl displayUrl: (NSString *) displayUrl offset: (int32_t) offset length: (int32_t) length properties: (NSMutableDictionary *) properties;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int) type;
- (void) setType: (int) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photoUrl;
- (void) setPhotoUrl: (NSString *) photoUrl;
#endif
- (BOOL) photoUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) expandedUrl;
- (void) setExpandedUrl: (NSString *) expandedUrl;
#endif
- (BOOL) expandedUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) displayUrl;
- (void) setDisplayUrl: (NSString *) displayUrl;
#endif
- (BOOL) displayUrlIsSet;

#if !__has_feature(objc_arc)
- (int32_t) offset;
- (void) setOffset: (int32_t) offset;
#endif
- (BOOL) offsetIsSet;

#if !__has_feature(objc_arc)
- (int32_t) length;
- (void) setLength: (int32_t) length;
#endif
- (BOOL) lengthIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) properties;
- (void) setProperties: (NSMutableDictionary *) properties;
#endif
- (BOOL) propertiesIsSet;

@end

@interface SocialTag : NSObject <NSCoding> {
  NSString * __id;
  int32_t __offset;
  int32_t __length;

  BOOL __id_isset;
  BOOL __offset_isset;
  BOOL __length_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, getter=offset, setter=setOffset:) int32_t offset;
@property (nonatomic, getter=length, setter=setLength:) int32_t length;
#endif

- (id) init;
- (id) initWithId: (NSString *) id offset: (int32_t) offset length: (int32_t) length;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) offset;
- (void) setOffset: (int32_t) offset;
#endif
- (BOOL) offsetIsSet;

#if !__has_feature(objc_arc)
- (int32_t) length;
- (void) setLength: (int32_t) length;
#endif
- (BOOL) lengthIsSet;

@end

@interface Hashtag : NSObject <NSCoding> {
  NSString * __text;
  int32_t __offset;
  int32_t __length;

  BOOL __text_isset;
  BOOL __offset_isset;
  BOOL __length_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, getter=offset, setter=setOffset:) int32_t offset;
@property (nonatomic, getter=length, setter=setLength:) int32_t length;
#endif

- (id) init;
- (id) initWithText: (NSString *) text offset: (int32_t) offset length: (int32_t) length;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

#if !__has_feature(objc_arc)
- (int32_t) offset;
- (void) setOffset: (int32_t) offset;
#endif
- (BOOL) offsetIsSet;

#if !__has_feature(objc_arc)
- (int32_t) length;
- (void) setLength: (int32_t) length;
#endif
- (BOOL) lengthIsSet;

@end

@interface MonitorLink : NSObject <NSCoding> {
  NSString * __photoUrl;
  NSString * __expandedUrl;
  NSString * __displayUrl;
  NSString * __name;
  NSString * __caption;
  NSString * __monitorLinkDescription;
  int32_t __offset;
  int32_t __length;

  BOOL __photoUrl_isset;
  BOOL __expandedUrl_isset;
  BOOL __displayUrl_isset;
  BOOL __name_isset;
  BOOL __caption_isset;
  BOOL __monitorLinkDescription_isset;
  BOOL __offset_isset;
  BOOL __length_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=photoUrl, setter=setPhotoUrl:) NSString * photoUrl;
@property (nonatomic, retain, getter=expandedUrl, setter=setExpandedUrl:) NSString * expandedUrl;
@property (nonatomic, retain, getter=displayUrl, setter=setDisplayUrl:) NSString * displayUrl;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=caption, setter=setCaption:) NSString * caption;
@property (nonatomic, retain, getter=monitorLinkDescription, setter=setMonitorLinkDescription:) NSString * monitorLinkDescription;
@property (nonatomic, getter=offset, setter=setOffset:) int32_t offset;
@property (nonatomic, getter=length, setter=setLength:) int32_t length;
#endif

- (id) init;
- (id) initWithPhotoUrl: (NSString *) photoUrl expandedUrl: (NSString *) expandedUrl displayUrl: (NSString *) displayUrl name: (NSString *) name caption: (NSString *) caption monitorLinkDescription: (NSString *) monitorLinkDescription offset: (int32_t) offset length: (int32_t) length;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) photoUrl;
- (void) setPhotoUrl: (NSString *) photoUrl;
#endif
- (BOOL) photoUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) expandedUrl;
- (void) setExpandedUrl: (NSString *) expandedUrl;
#endif
- (BOOL) expandedUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) displayUrl;
- (void) setDisplayUrl: (NSString *) displayUrl;
#endif
- (BOOL) displayUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) caption;
- (void) setCaption: (NSString *) caption;
#endif
- (BOOL) captionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) monitorLinkDescription;
- (void) setMonitorLinkDescription: (NSString *) monitorLinkDescription;
#endif
- (BOOL) monitorLinkDescriptionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) offset;
- (void) setOffset: (int32_t) offset;
#endif
- (BOOL) offsetIsSet;

#if !__has_feature(objc_arc)
- (int32_t) length;
- (void) setLength: (int32_t) length;
#endif
- (BOOL) lengthIsSet;

@end

@interface MonitorPost : NSObject <NSCoding> {
  NSString * __id;
  NSString * __externalID;
  NSString * __source;
  NSString * __postUrl;
  PostUser * __user;
  NSString * __text;
  NSMutableArray * __links;
  NSMutableArray * __medias;
  NSMutableArray * __tags;
  NSMutableArray * __hashtags;
  NSMutableDictionary * __properties;
  int64_t __created;
  int64_t __updated;
  int64_t __latestReplyTime;
  int32_t __numReplies;
  int32_t __numRepliesFromSelf;
  BOOL __flagged;
  BOOL __read;
  BOOL __upvoted;
  BOOL __deletable;
  Source * __basicSourceInfo;
  NSMutableArray * __allowedActions;

  BOOL __id_isset;
  BOOL __externalID_isset;
  BOOL __source_isset;
  BOOL __postUrl_isset;
  BOOL __user_isset;
  BOOL __text_isset;
  BOOL __links_isset;
  BOOL __medias_isset;
  BOOL __tags_isset;
  BOOL __hashtags_isset;
  BOOL __properties_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __latestReplyTime_isset;
  BOOL __numReplies_isset;
  BOOL __numRepliesFromSelf_isset;
  BOOL __flagged_isset;
  BOOL __read_isset;
  BOOL __upvoted_isset;
  BOOL __deletable_isset;
  BOOL __basicSourceInfo_isset;
  BOOL __allowedActions_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=externalID, setter=setExternalID:) NSString * externalID;
@property (nonatomic, retain, getter=source, setter=setSource:) NSString * source;
@property (nonatomic, retain, getter=postUrl, setter=setPostUrl:) NSString * postUrl;
@property (nonatomic, retain, getter=user, setter=setUser:) PostUser * user;
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, retain, getter=links, setter=setLinks:) NSMutableArray * links;
@property (nonatomic, retain, getter=medias, setter=setMedias:) NSMutableArray * medias;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSMutableArray * tags;
@property (nonatomic, retain, getter=hashtags, setter=setHashtags:) NSMutableArray * hashtags;
@property (nonatomic, retain, getter=properties, setter=setProperties:) NSMutableDictionary * properties;
@property (nonatomic, getter=created, setter=setCreated:) int64_t created;
@property (nonatomic, getter=updated, setter=setUpdated:) int64_t updated;
@property (nonatomic, getter=latestReplyTime, setter=setLatestReplyTime:) int64_t latestReplyTime;
@property (nonatomic, getter=numReplies, setter=setNumReplies:) int32_t numReplies;
@property (nonatomic, getter=numRepliesFromSelf, setter=setNumRepliesFromSelf:) int32_t numRepliesFromSelf;
@property (nonatomic, getter=flagged, setter=setFlagged:) BOOL flagged;
@property (nonatomic, getter=read, setter=setRead:) BOOL read;
@property (nonatomic, getter=upvoted, setter=setUpvoted:) BOOL upvoted;
@property (nonatomic, getter=deletable, setter=setDeletable:) BOOL deletable;
@property (nonatomic, retain, getter=basicSourceInfo, setter=setBasicSourceInfo:) Source * basicSourceInfo;
@property (nonatomic, retain, getter=allowedActions, setter=setAllowedActions:) NSMutableArray * allowedActions;
#endif

- (id) init;
- (id) initWithId: (NSString *) id externalID: (NSString *) externalID source: (NSString *) source postUrl: (NSString *) postUrl user: (PostUser *) user text: (NSString *) text links: (NSMutableArray *) links medias: (NSMutableArray *) medias tags: (NSMutableArray *) tags hashtags: (NSMutableArray *) hashtags properties: (NSMutableDictionary *) properties created: (int64_t) created updated: (int64_t) updated latestReplyTime: (int64_t) latestReplyTime numReplies: (int32_t) numReplies numRepliesFromSelf: (int32_t) numRepliesFromSelf flagged: (BOOL) flagged read: (BOOL) read upvoted: (BOOL) upvoted deletable: (BOOL) deletable basicSourceInfo: (Source *) basicSourceInfo allowedActions: (NSMutableArray *) allowedActions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) externalID;
- (void) setExternalID: (NSString *) externalID;
#endif
- (BOOL) externalIDIsSet;

#if !__has_feature(objc_arc)
- (NSString *) source;
- (void) setSource: (NSString *) source;
#endif
- (BOOL) sourceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) postUrl;
- (void) setPostUrl: (NSString *) postUrl;
#endif
- (BOOL) postUrlIsSet;

#if !__has_feature(objc_arc)
- (PostUser *) user;
- (void) setUser: (PostUser *) user;
#endif
- (BOOL) userIsSet;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) links;
- (void) setLinks: (NSMutableArray *) links;
#endif
- (BOOL) linksIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) medias;
- (void) setMedias: (NSMutableArray *) medias;
#endif
- (BOOL) mediasIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tags;
- (void) setTags: (NSMutableArray *) tags;
#endif
- (BOOL) tagsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) hashtags;
- (void) setHashtags: (NSMutableArray *) hashtags;
#endif
- (BOOL) hashtagsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) properties;
- (void) setProperties: (NSMutableDictionary *) properties;
#endif
- (BOOL) propertiesIsSet;

#if !__has_feature(objc_arc)
- (int64_t) created;
- (void) setCreated: (int64_t) created;
#endif
- (BOOL) createdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) updated;
- (void) setUpdated: (int64_t) updated;
#endif
- (BOOL) updatedIsSet;

#if !__has_feature(objc_arc)
- (int64_t) latestReplyTime;
- (void) setLatestReplyTime: (int64_t) latestReplyTime;
#endif
- (BOOL) latestReplyTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) numReplies;
- (void) setNumReplies: (int32_t) numReplies;
#endif
- (BOOL) numRepliesIsSet;

#if !__has_feature(objc_arc)
- (int32_t) numRepliesFromSelf;
- (void) setNumRepliesFromSelf: (int32_t) numRepliesFromSelf;
#endif
- (BOOL) numRepliesFromSelfIsSet;

#if !__has_feature(objc_arc)
- (BOOL) flagged;
- (void) setFlagged: (BOOL) flagged;
#endif
- (BOOL) flaggedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) read;
- (void) setRead: (BOOL) read;
#endif
- (BOOL) readIsSet;

#if !__has_feature(objc_arc)
- (BOOL) upvoted;
- (void) setUpvoted: (BOOL) upvoted;
#endif
- (BOOL) upvotedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) deletable;
- (void) setDeletable: (BOOL) deletable;
#endif
- (BOOL) deletableIsSet;

#if !__has_feature(objc_arc)
- (Source *) basicSourceInfo;
- (void) setBasicSourceInfo: (Source *) basicSourceInfo;
#endif
- (BOOL) basicSourceInfoIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) allowedActions;
- (void) setAllowedActions: (NSMutableArray *) allowedActions;
#endif
- (BOOL) allowedActionsIsSet;

@end

@interface FeedResponse : NSObject <NSCoding> {
  Response * __response;
  int64_t __count;
  NSMutableArray * __items;

  BOOL __response_isset;
  BOOL __count_isset;
  BOOL __items_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, getter=count, setter=setCount:) int64_t count;
@property (nonatomic, retain, getter=items, setter=setItems:) NSMutableArray * items;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response count: (int64_t) count items: (NSMutableArray *) items;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (int64_t) count;
- (void) setCount: (int64_t) count;
#endif
- (BOOL) countIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) items;
- (void) setItems: (NSMutableArray *) items;
#endif
- (BOOL) itemsIsSet;

@end

@interface PermissionsResponse : NSObject <NSCoding> {
  Response * __response;
  UserConfig * __config;

  BOOL __response_isset;
  BOOL __config_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=config, setter=setConfig:) UserConfig * config;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response config: (UserConfig *) config;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (UserConfig *) config;
- (void) setConfig: (UserConfig *) config;
#endif
- (BOOL) configIsSet;

@end

@interface SaveConfigResponse : NSObject <NSCoding> {
  Response * __response;
  NSMutableArray * __userSettings;

  BOOL __response_isset;
  BOOL __userSettings_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=userSettings, setter=setUserSettings:) NSMutableArray * userSettings;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response userSettings: (NSMutableArray *) userSettings;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) userSettings;
- (void) setUserSettings: (NSMutableArray *) userSettings;
#endif
- (BOOL) userSettingsIsSet;

@end

@interface ReferenceDataResponse : NSObject <NSCoding> {
  Response * __response;
  ReferenceData * __cachedData;
  int64_t __ttl;

  BOOL __response_isset;
  BOOL __cachedData_isset;
  BOOL __ttl_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=cachedData, setter=setCachedData:) ReferenceData * cachedData;
@property (nonatomic, getter=ttl, setter=setTtl:) int64_t ttl;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response cachedData: (ReferenceData *) cachedData ttl: (int64_t) ttl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (ReferenceData *) cachedData;
- (void) setCachedData: (ReferenceData *) cachedData;
#endif
- (BOOL) cachedDataIsSet;

#if !__has_feature(objc_arc)
- (int64_t) ttl;
- (void) setTtl: (int64_t) ttl;
#endif
- (BOOL) ttlIsSet;

@end

@interface RatingResponse : NSObject <NSCoding> {
  Response * __response;
  NSString * __ratingID;

  BOOL __response_isset;
  BOOL __ratingID_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=ratingID, setter=setRatingID:) NSString * ratingID;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response ratingID: (NSString *) ratingID;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (NSString *) ratingID;
- (void) setRatingID: (NSString *) ratingID;
#endif
- (BOOL) ratingIDIsSet;

@end

@interface SummaryResponse : NSObject <NSCoding> {
  Response * __response;
  NSMutableArray * __aggregates;

  BOOL __response_isset;
  BOOL __aggregates_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=aggregates, setter=setAggregates:) NSMutableArray * aggregates;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response aggregates: (NSMutableArray *) aggregates;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) aggregates;
- (void) setAggregates: (NSMutableArray *) aggregates;
#endif
- (BOOL) aggregatesIsSet;

@end

@interface SocialFeedResponse : NSObject <NSCoding> {
  Response * __response;
  NSMutableArray * __socialPosts;

  BOOL __response_isset;
  BOOL __socialPosts_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=socialPosts, setter=setSocialPosts:) NSMutableArray * socialPosts;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response socialPosts: (NSMutableArray *) socialPosts;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) socialPosts;
- (void) setSocialPosts: (NSMutableArray *) socialPosts;
#endif
- (BOOL) socialPostsIsSet;

@end

@protocol Mobile <NSObject>
- (FeedResponse *) getReviewsFeed: (int64_t) uptoTime start: (int32_t) start pageCount: (int32_t) pageCount searchCriteria: (SearchFilter *) searchCriteria;  // throws TException
- (SocialFeedResponse *) getSocialFeed: (int64_t) uptoTime start: (int32_t) start pageCount: (int32_t) pageCount searchCriteria: (SearchFilter *) searchCriteria;  // throws TException
- (ReferenceDataResponse *) getReferenceData;  // throws TException
- (PermissionsResponse *) getUserConfig;  // throws TException
- (SaveConfigResponse *) saveUserConfig: (NSMutableArray *) userSettings;  // throws TException
- (RatingResponse *) publishRating: (NSString *) ratingID isUnpublish: (BOOL) isUnpublish;  // throws TException
- (RatingResponse *) deleteRating: (NSString *) ratingID;  // throws TException
- (RatingResponse *) replyToRating: (NSString *) ratingID recepientEmail: (NSString *) recepientEmail message: (NSString *) message isForward: (BOOL) isForward;  // throws TException
- (SummaryResponse *) getSummary;  // throws TException
- (Response *) logout;  // throws TException
@end

@interface MobileClient : NSObject <Mobile> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface MobileProcessor : NSObject <TProcessor> {
  id <Mobile> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithMobile: (id <Mobile>) service;
- (id<Mobile>) service;
@end

@interface MobileConstants : NSObject {
}
+ (NSString *) SUMMARY_OVERALL_SCORE;
+ (NSString *) SUMMARY_AVGRATING_SOURCE;
+ (NSString *) SUMMARY_NOREVIEWS_SOURCE;
+ (NSString *) SUMMARY_SOCIALCOUNTS_SOURCE;
+ (NSString *) SUMMARY_OVERALL_SCORE_VALUE;
+ (NSString *) SUMMARY_OVERALL_SCORE_WEIGHTEDRATING;
+ (NSString *) SUMMARY_OVERALL_SCORE_VISIBILITY;
+ (NSString *) SUMMARY_OVERALL_SCORE_SPREAD;
+ (NSString *) SUMMARY_OVERALL_SCORE_LENGTH;
+ (NSString *) SUMMARY_OVERALL_SCORE_TIME;
+ (NSString *) SUMMARY_OVERALL_SCORE_VOLUME;
+ (NSString *) SUMMARY_OVERALL_SCORE_WEIGHTEDRATING_FILLCOLOR;
+ (NSString *) SUMMARY_OVERALL_SCORE_VISIBILITY_FILLCOLOR;
+ (NSString *) SUMMARY_OVERALL_SCORE_SPREAD_FILLCOLOR;
+ (NSString *) SUMMARY_OVERALL_SCORE_LENGTH_FILLCOLOR;
+ (NSString *) SUMMARY_OVERALL_SCORE_TIME_FILLCOLOR;
+ (NSString *) SUMMARY_OVERALL_SCORE_VOLUME_FILLCOLOR;
+ (NSString *) SUMMARY_NOREVIEWS_SOURCELOGO;
+ (NSString *) SUMMARY_NOREVIEWS_SOURCENAME;
+ (NSString *) SUMMARY_SOURCE_LOGO_URL;
+ (NSString *) SUMMARY_SOURCE_NAME;
@end
